### ISSUE TITLE
[FRONTEND] Add resusable hook into project

### ISSUE THREAD

**Issue by epoundor** [Frelya/react-site-editor#24]

**Comment by YacineSteeve** [comment]
* What is the purpose/usecases of the hooks you add in #25 ?

**Comment by YacineSteeve** [comment]
> * @epoundor , what is the purpose/usecases of the hooks you add in [Add `Storage` hooks #25](https://github.com/Frelya/react-site-editor/pull/25) ?

Oh, Is it for storing the whole `html` currently in the `iframe` at a given moment ?
