### ISSUE TITLE
[FRONTEND] Add React Tooltip into the project

### ISSUE THREAD

**Issue by epoundor** [Frelya/react-site-editor#32]
https://www.npmjs.com/package/react-tooltip

**Comment by YacineSteeve** [comment]
Can you provide a better description of the task, please?
Instead of a simple link to a ressource...

**Comment by epoundor** [comment]
> Can you provide a better description of the task, please? Instead of a simple link to a ressource... Something like the reason of the feature or the fix, the usage/behavior expected, etc...

I saw that you put 'description' as a property of the icons. I assumed that this is to display a tooltip beneath the icon to explain its function.

We will likely use tooltips to clearly explain situations. Hence this.
